version: "3"

services:
  api:
    user:
      node
    build:
      context: .
      dockerfile: docker/workplace/Dockerfile
    env_file:
      - .env
      - .env.docker
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/home/node/app/
    command: npm run start:docker-workplace

  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
