workstation:
	docker-compose --env-file ./config/.env up -d
test:
	docker-compose --env-file ./config/.env.test up -d
dev:
	docker-compose --env-file ./config/.env.dev up -d
prod:
	docker-compose --env-file ./config/.env.prod up -d
