name: API Test
on:
  push:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install make
        run: sudo apt install make
      - name: Start required services
        working-directory: ./api
        run: make test
      - name: Install
        working-directory: ./api
        run: npm install
      - name: Run tests
        working-directory: ./api
        run: npm run test
      - name: Run e2e tests
        working-directory: ./api
        run: npm run test:e2e
