name: webapp test
on:
  push:
    branches:
      - main
    paths:
      - 'webapp/**'

jobs:
  test-webapp:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        working-directory: ./webapp
        run: npm install
      - name: Run tests
        working-directory: ./webapp
        run: npm run test
